[package]
name = "zicc"
version.workspace = true
edition.workspace = true
description = "Zanna's IntCode Compiler"

[workspace]
resolver = "3"
members = [
  "assembler/ast",
  "assembler/parser",
  "compiler",
  "compiler/ast",
  "compiler/lexer",
  "compiler/parser",
  "compiler/types",
  "utils/*",
  "utils/test_crawler",
  "vm",
  "vm/program",
  "vm/stream"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
zicc-assembler-ast = { path = "assembler/ast" }
zicc-compiler-ast = { path = "compiler/ast" }
zicc-compiler-lexer = { path = "compiler/lexer" }
zicc-frontmatter = { path = "utils/frontmatter" }
zicc-intcode = { path = "utils/intcode" }
zicc-limits = { path = "utils/limits" }
zicc-value = { path = "utils/value" }
zicc-vm = { path = "vm" }
zicc-vm-program = { path = "vm/program" }
zicc-vm-stream = { path = "vm/stream" }
zicc-test-crawler = { path = "utils/test_crawler" }

ariadne = "0.6.0"

chumsky = "1.0.0-alpha.8"
clap = { version = "4.6.1", features = ["derive"] }

derive_more = { version = "2.1.1", features = ["full"] }

lazy-regex = "3.6.0"

serde = { version = "1.0.228", features = ["derive", "rc"] }
snafu = "0.9.0"
string-interner = "0.19.0"
toml = "1.1.2"

[dependencies]
zicc-vm.workspace = true

clap.workspace = true
snafu.workspace = true
