[package]
name = "zicc-vm"
version.workspace = true
edition.workspace = true
description = "Intcode virtual machine"

[dependencies]
zicc-intcode.workspace = true
zicc-limits.workspace = true
zicc-vm-program.workspace = true
zicc-vm-stream.workspace = true

clap.workspace = true
clap-stdin.workspace = true
derive_more.workspace = true
serde.workspace = true
snafu.workspace = true
