[package]
name = "zicc-vm"
version.workspace = true
edition.workspace = true

[dependencies]
zicc-frontmatter.workspace = true
zicc-intcode.workspace = true
zicc-limits.workspace = true

clap.workspace = true
derive_more.workspace = true
itertools.workspace = true
lazy-regex.workspace = true
serde.workspace = true
snafu.workspace = true
