[package]
name = "zicc-compiler-lexer"
version.workspace = true
edition.workspace = true

[dependencies]
derive_more.workspace = true
lazy-regex.workspace = true
logos = "0.16.1"
macro_rules_attribute = "0.2.2"
paste = "1.0.15"
string-interner.workspace = true
zicc-display.workspace = true
zicc-limits.workspace = true

[dev-dependencies]
ariadne.workspace = true
assert_matches = "1.5.0"
clap.workspace = true
