[package]
name = "zicc-compiler-lexer"
version.workspace = true
edition.workspace = true

[dependencies]
derive_more.workspace = true
lazy-regex = "3.6.0"
logos = "0.16.1"
macro_rules_attribute = "0.2.2"
num = { version = "0.4.3", features = ["num-bigint"] }
paste = "1.0.15"
snafu = "0.9.0"
string-interner.workspace = true

[dev-dependencies]
ariadne = "0.6.0"
assert_matches = "1.5.0"
clap.workspace = true
