[package]
name = "zicc-test-crawler"
version.workspace = true
edition.workspace = true
description = "Test source crawling utilities for IntCode compiler toolchain tests"

[dependencies]
zicc-vm-program.workspace = true

cargo-emit = "0.2.1"
glob = "0.3.3"
proc-macro2 = "1.0.106"
quote = "1.0.45"
serde.workspace = true
slugify = "0.1.0"
