[package]
name = "assembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.1"
itertools = "0.11.0"
lazy-regex = "2.5.0"
smartstring = "1.0.1"
thiserror = "1.0.40"

[dev-dependencies]
strum = { version = "0.25.0", features = ["derive"] }
