[package]
name = "zicc-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
zicc-assembler-program.workspace = true
zicc-compiler-ast.workspace = true
zicc-compiler-lexer.workspace = true
zicc-compiler-program.workspace = true
zicc-compiler-types.workspace = true
zicc-limits.workspace = true

ariadne.workspace = true
clap.workspace = true
clap-stdin.workspace = true
snafu.workspace = true
string-interner.workspace = true
