[package]
name = "spans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nonmax = "0.5.5"
string-interner = "0.17.0"
