[package]
name = "zicc-compiler-parser"
version.workspace = true
edition.workspace = true

[dependencies]
zicc-compiler-ast.workspace = true
zicc-compiler-lexer.workspace = true

chumsky.workspace = true
string-interner.workspace = true

[dev-dependencies]
ariadne.workspace = true
clap.workspace = true
