[package]
name = "keyword_expand"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
convert_case = "0.6.0"
either = "1.9.0"
itertools = "0.11.0"
lazy-regex = "3.0.2"
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = "2.0.38"
